version: "3.7"

services:
  postgres:
    image: pgvector/pgvector:pg16
    volumes:
      - hotwire-example-template-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: "redis:6.2.7-alpine"
    ports:
      - "6379:6379"

volumes:
  hotwire-example-template-volume:
    external: false
